version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            sudo npm i -g @serverless/cli
            npm install

      - save_cache:
          key: dependency-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./.next/cache
        
      - run:
          name: Set version number and branch in env
          command: |
              echo 'export NEXT_PUBLIC_VERSION=$CIRCLE_BUILD_NUM' >> $BASH_ENV
              echo 'export NEXT_PUBLIC_BRANCH=$CIRCLE_BRANCH' >> $BASH_ENV
              echo 'export NEXT_PUBLIC_BUCKET=blob-images-frontend-$CIRCLE_BRANCH' >> $BASH_ENV
              source $BASH_ENV

      # run tests!
      - run: 
          name: Run tests with coverage
          command: npm test --coverage

      - run:
          name: Build production version
          command: npm run build
      
      - run:
          name: Create registry as workaround for serverless bug
          command: |
            mkdir -p /home/circleci/.serverless/components/registry/npm/@sls-next/serverless-component@1.17.0
            mkdir -p /home/circleci/.serverless/components/registry/npm/@sls-next/serverless-component@1.18.0-alpha.27

      - run:
          name: Deploy application
          command: serverless