version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./.next/cache
        
      - run:
        name: The current version number
        command: echo $CIRCLE_BUILD_NUM

      - run:
          name: Set version number and branch in env
          command: |
              echo 'export NEXT_PUBLIC_VERSION=$CIRCLE_BUILD_NUM' >> $BASH_ENV
              echo 'export NEXT_PUBLIC_BRANCH=$CIRCLE_BRANCH' >> $BASH_ENV
              echo 'export NEXT_PUBLIC_DOMAIN=dev.clubalmanac.com' >> $BASH_ENV
              source $BASH_ENV

      # run tests!
      - run: 
          name: Run tests with coverage
          command: npm test --coverage

      - run:
          name: Build production version
          command: npm run build
      
      - run:
          name: Deploy application
          command: npx serverless